Improve ChangeLog generation rules.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -19,29 +19,15 @@ EXTRA_DIST = \
 	$(doc_DATA) \
 	$(NULL)
 
-CLEANFILES = \
-	$(srcdir)/ChangeLog \
+DISTCLEANFILES = \
+	ChangeLog \
 	$(NULL)
 
-distclean-local:
-	if test "$(srcdir)" = "."; then \
-	  :; \
-	else \
-	  rm -f ChangeLog; \
-	fi
-
 ChangeLog:
-	@echo Creating $@
-	@if test -d "$(srcdir)/.git"; then \
-	  (GIT_DIR=$(top_srcdir)/.git $(top_srcdir)/missing --run git log --stat) > $@.tmp \
-	  && mv -f $@.tmp $@ \
-	  || ($(RM) $@.tmp; \
-	  echo Failed to generate ChangeLog, your ChangeLog may be outdated >&2; \
-	  (test -f $@ || echo git-log is required to generate this file >> $@)); \
-	else \
-	  test -f $@ || \
-	  (echo A git checkout and git-log is required to generate ChangeLog >&2 && \
-	  echo A git checkout and git-log is required to generate this file >> $@); \
-	fi
+	$(AM_V_GEN) \
+	(GIT_DIR=$(top_srcdir)/.git $(top_srcdir)/missing --run git log --stat) >$@.tmp 2>/dev/null\
+	&& mv -f $@.tmp $@ \
+	|| ($(RM) $@.tmp; \
+	echo "         Could not generate ChangeLog, your ChangeLog may be outdated" >&2)
 
 .PHONY: ChangeLog
